Repository apache/accumulo, pull requests merged in 2018-09, with the labels that each got.

#625 Stop sending error message in bean validation response
  server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
Labels: v2.0.0

#630 Switched to using HADOOP_HOME for Hadoop 3.x
  INSTALL.md
  assemble/bin/accumulo-util
  assemble/conf/accumulo-env.sh
  minicluster/src/main/java/org/apache/accumulo/minicluster/impl/MiniAccumuloClusterImpl.java
Labels: enhancement, v2.0.0

#629 Fix warnings from dependency updates
  core/src/main/java/org/apache/accumulo/core/client/ClientConfiguration.java
  core/src/main/java/org/apache/accumulo/core/client/impl/BulkSerialize.java
  core/src/main/java/org/apache/accumulo/core/client/sample/AbstractHashSampler.java
  core/src/main/java/org/apache/accumulo/core/client/summary/SummarizerConfiguration.java
  core/src/main/java/org/apache/accumulo/core/data/Value.java
  core/src/main/java/org/apache/accumulo/core/sample/impl/DataoutputHasher.java
  core/src/main/java/org/apache/accumulo/core/security/crypto/CryptoUtils.java
  core/src/main/java/org/apache/accumulo/core/summary/Gatherer.java
  core/src/main/java/org/apache/accumulo/core/util/HostAndPort.java
  core/src/main/spotbugs/exclude-filter.xml
  core/src/test/java/org/apache/accumulo/core/conf/PropertyTypeTest.java
  core/src/test/java/org/apache/accumulo/core/data/KeyBuilderTest.java
  core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
  server/base/src/main/java/org/apache/accumulo/server/fs/VolumeUtil.java
  server/base/src/test/java/org/apache/accumulo/server/util/TServerUtilsTest.java
  server/master/src/main/java/org/apache/accumulo/master/MasterTime.java
  shell/src/main/java/org/apache/accumulo/shell/Shell.java
  shell/src/main/java/org/apache/accumulo/shell/commands/ShellPluginConfigurationCommand.java
  shell/src/test/java/org/apache/accumulo/shell/ShellUtilTest.java
  test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
Labels: v2.0.0

#651 Correct how Continuous Ingest specifies the debug log file
  test/system/continuous/start-ingest.sh
Labels: bug, v1.9.3

#654 AccumuloFileOutputFormatITs need to look on local filesystem for results written into JUnit provided temp dir.
  test/src/main/java/org/apache/accumulo/test/mapred/AccumuloFileOutputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloFileOutputFormatIT.java
Labels: v1.9.3, v2.0.0

#655 Remove httpclient dependency.
  core/pom.xml
  examples/simple/pom.xml
  maven-plugin/pom.xml
  maven-plugin/src/it/plugin-test/pom.xml
  maven-plugin/src/main/java/org/apache/accumulo/maven/plugin/StartMojo.java
  maven-plugin/src/main/java/org/apache/accumulo/maven/plugin/StopMojo.java
  pom.xml
  test/pom.xml
Labels: v1.9.3, v2.0.0

#659 Update commons-configuration to latest 1.x on branch 1.9
  core/src/main/java/org/apache/accumulo/core/client/ClientConfiguration.java
  pom.xml
Labels: v1.9.3
