Repository apache/accumulo, pull requests merged in 2018-06, with the labels that each got.

#514 Correct error msg when importing a table with incompatible data version
  server/master/src/main/java/org/apache/accumulo/master/tableOps/ImportTable.java
Labels: bug, v2.0.0

#531 Use Hadoop 3 exclusively for Accumulo 2.0
  assemble/pom.xml
  assemble/src/main/assemblies/binary-release-hadoop3.xml
  assemble/src/main/assemblies/component-hadoop3.xml
  assemble/src/main/assemblies/component.xml
  client/mapreduce/pom.xml
  core/pom.xml
  iterator-test-harness/pom.xml
  maven-plugin/src/it/plugin-test/pom.xml
  minicluster/pom.xml
  pom.xml
  proxy/pom.xml
  server/base/pom.xml
  server/gc/pom.xml
  server/master/pom.xml
  server/monitor/pom.xml
  server/tracer/pom.xml
  server/tserver/pom.xml
  shell/pom.xml
  start/pom.xml
  test/pom.xml
Labels: blocker, enhancement, v2.0.0

#539 Fix WAL race condition between zookeeper and metadata table
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: blocker, bug, v1.9.2, v2.0.0
