Repository apache/accumulo, pull requests merged in 2018-04, with the labels that each got.

#417 Make TLSv1.2 the default
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
Labels: v1.9.0, v2.0.0

#429 Handle RW unexpected table state
  test/src/main/java/org/apache/accumulo/test/randomwalk/concurrent/OfflineTable.java
Labels: v1.9.1

#430 #408 - Removed uses of deprecated ClientConfiguration
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloMultiTableInputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloOutputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloMultiTableInputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/ConfiguratorBase.java
  core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
  core/src/main/java/org/apache/accumulo/core/client/impl/ClientConfConverter.java
  core/src/main/java/org/apache/accumulo/core/client/impl/ClientContext.java
  core/src/main/java/org/apache/accumulo/core/rpc/SaslConnectionParams.java
  core/src/main/java/org/apache/accumulo/core/trace/DistributedTrace.java
  core/src/test/java/org/apache/accumulo/core/client/ClientConfigurationTest.java
  core/src/test/java/org/apache/accumulo/core/client/ZooKeeperInstanceTest.java
  core/src/test/java/org/apache/accumulo/core/client/impl/ClientContextTest.java
  core/src/test/java/org/apache/accumulo/core/client/impl/TableOperationsImplTest.java
  core/src/test/java/org/apache/accumulo/core/client/impl/TabletLocatorImplTest.java
  core/src/test/java/org/apache/accumulo/core/client/impl/ThriftTransportKeyTest.java
  core/src/test/java/org/apache/accumulo/core/rpc/SaslConnectionParamsTest.java
  proxy/src/main/java/org/apache/accumulo/proxy/Proxy.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/SaslServerConnectionParams.java
  server/base/src/main/java/org/apache/accumulo/server/util/RemoveEntriesForMissingFiles.java
  server/base/src/main/java/org/apache/accumulo/server/util/VerifyTabletAssignments.java
  server/base/src/test/java/org/apache/accumulo/server/AccumuloServerContextTest.java
  server/base/src/test/java/org/apache/accumulo/server/rpc/SaslServerConnectionParamsTest.java
  server/tserver/src/test/java/org/apache/accumulo/tserver/replication/ReplicationProcessorTest.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloInputFormatIT.java
Labels: v2.0.0

#447 Remove unused WAL props
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  core/src/test/java/org/apache/accumulo/core/conf/ConfigSanityCheckTest.java
Labels: v2.0.0

#443 fixes #441 only dereference WALs after minc finishes
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: blocker, bug, v1.9.1, v2.0.0
