Repository apache/accumulo, pull requests merged in 2018-07, with the labels that each got.

#553 Correct display of BulkImport duration in monitor
  core/src/main/java/org/apache/accumulo/core/util/Duration.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/servlets/BulkImportServlet.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/util/celltypes/DurationType.java
Labels: v1.9.2

#546 Fix multiple concurrency bugs in Master.gatherTableInformation()
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
Labels: blocker, bug, v1.9.2, v2.0.0

#562 Fix array out of bounds in FastFormat
  core/src/main/java/org/apache/accumulo/core/util/FastFormat.java
  core/src/test/java/org/apache/accumulo/core/util/FastFormatTest.java
Labels: v1.9.3, v2.0.0

#568 bugfix/WAL-configuration
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
Labels: v2.0.0
