Repository apache/accumulo, pull requests merged in 2018-10, with the labels that each got.

#673 Fixes #561 - Be explicit about aliases in shell
  shell/src/main/java/org/apache/accumulo/shell/commands/DeleteTableCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/DropTableCommand.java
Labels: v2.0.0

#675 Fix script to build native libs
  assemble/bin/accumulo-util
Labels: v2.0.0

#686 Fix #684 Move accumulo-maven-plugin from build
  maven-plugin/.gitignore
  maven-plugin/pom.xml
  maven-plugin/src/it/plugin-test/pom.xml
  maven-plugin/src/it/plugin-test/postbuild.groovy
  maven-plugin/src/it/plugin-test/src/main/java/org/apache/accumulo/plugin/CustomFilter.java
  maven-plugin/src/it/plugin-test/src/test/java/org/apache/accumulo/plugin/it/PluginIT.java
  maven-plugin/src/it/settings.xml
  maven-plugin/src/main/java/org/apache/accumulo/maven/plugin/AbstractAccumuloMojo.java
  maven-plugin/src/main/java/org/apache/accumulo/maven/plugin/StartMojo.java
  maven-plugin/src/main/java/org/apache/accumulo/maven/plugin/StopMojo.java
  maven-plugin/src/main/spotbugs/exclude-filter.xml
  pom.xml
Labels: v2.0.0

#689 Cleanup deprecation stuffs
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
  client/mapreduce/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/impl/ConfiguratorBase.java
  core/src/main/java/org/apache/accumulo/core/client/impl/AccumuloClientImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/ClientContext.java
  core/src/main/java/org/apache/accumulo/core/client/summary/Summary.java
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  core/src/main/java/org/apache/accumulo/core/util/format/BinaryFormatter.java
  core/src/main/java/org/apache/accumulo/core/util/format/DateStringFormatter.java
  minicluster/src/main/java/org/apache/accumulo/cluster/AccumuloCluster.java
  minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloCluster.java
  minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterExistingZooKeepersTest.java
  minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterStartStopTest.java
  minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
Labels: v2.0.0

#690 Remove aggregators
  core/pom.xml
  core/src/main/java/org/apache/accumulo/core/Constants.java
  core/src/main/java/org/apache/accumulo/core/client/ClientSideIteratorScanner.java
  core/src/main/java/org/apache/accumulo/core/client/Connector.java
  core/src/main/java/org/apache/accumulo/core/client/IsolatedScanner.java
  core/src/main/java/org/apache/accumulo/core/client/Scanner.java
  core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
  core/src/main/java/org/apache/accumulo/core/client/admin/SecurityOperations.java
  core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
  core/src/main/java/org/apache/accumulo/core/client/impl/AccumuloClientImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/ConnectorImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/OfflineScanner.java
  core/src/main/java/org/apache/accumulo/core/client/impl/ScannerImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/ScannerIterator.java
  core/src/main/java/org/apache/accumulo/core/client/impl/SecurityOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/ThriftScanner.java
  core/src/main/java/org/apache/accumulo/core/client/rfile/RFileScanner.java
  core/src/main/java/org/apache/accumulo/core/client/security/tokens/KerberosToken.java
  core/src/main/java/org/apache/accumulo/core/constraints/Constraint.java
  core/src/main/java/org/apache/accumulo/core/data/PartialKey.java
  core/src/main/java/org/apache/accumulo/core/data/Value.java
  core/src/main/java/org/apache/accumulo/core/data/impl/KeyExtent.java
  core/src/main/java/org/apache/accumulo/core/iterators/AggregatingIterator.java
  core/src/main/java/org/apache/accumulo/core/iterators/FamilyIntersectingIterator.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/Aggregator.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/LongSummation.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/NumArraySummation.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/NumSummation.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/StringMax.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/StringMin.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/StringSummation.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/conf/AggregatorConfiguration.java
  core/src/main/java/org/apache/accumulo/core/iterators/aggregation/conf/AggregatorSet.java
  core/src/main/java/org/apache/accumulo/core/iterators/conf/PerColumnIteratorConfig.java
  core/src/main/java/org/apache/accumulo/core/iterators/user/IntersectingIterator.java
  core/src/main/java/org/apache/accumulo/core/trace/Trace.java
  core/src/test/java/org/apache/accumulo/core/client/impl/TableOperationsHelperTest.java
  core/src/test/java/org/apache/accumulo/core/data/KeyExtentTest.java
  core/src/test/java/org/apache/accumulo/core/data/ValueTest.java
  core/src/test/java/org/apache/accumulo/core/iterators/AggregatingIteratorTest.java
  core/src/test/java/org/apache/accumulo/core/iterators/aggregation/NumSummationTest.java
  core/src/test/java/org/apache/accumulo/core/iterators/aggregation/conf/AggregatorConfigurationTest.java
  proxy/src/main/java/org/apache/accumulo/proxy/ProxyServer.java
  server/tracer/src/test/java/org/apache/accumulo/tracer/TracerTest.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TservConstraintEnv.java
  shell/src/main/java/org/apache/accumulo/shell/commands/SetIterCommand.java
  shell/src/test/java/org/apache/accumulo/shell/commands/SetIterCommandTest.java
  test/src/main/java/org/apache/accumulo/test/NewTableConfigurationIT.java
  test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
Labels: v2.0.0

#688 Cleanup Monitor log page
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/logs/LogEvent.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/logs/LogResource.java
  server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/css/screen.css
  server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/images/details_close.png
  server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/images/details_open.png
  server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/log.ftl
Labels: v2.0.0

#692 Remove key provider from crypto
  core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESCryptoService.java
  core/src/main/java/org/apache/accumulo/core/security/crypto/impl/AESKeyUtils.java
  core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
  test/src/main/java/org/apache/accumulo/test/functional/WriteAheadLogEncryptedIT.java
Labels: v2.0.0

#704 ACCUMULO-4818 Upgrade to checkstyle 8.13
  pom.xml
Labels: v2.0.0

#707 Fix summarizer bug with empty loc group
  core/src/main/java/org/apache/accumulo/core/summary/SummarySerializer.java
  test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
Labels: bug, v2.0.0

#714 Fix #713 Monitor 2.0 overview plots overlap when resizing browser window
  server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/default.ftl
Labels: v2.0.0

#728 Revert commons-vfs2 version
  pom.xml
Labels: v1.9.3

#737 Added Authorization Summarizer
  core/src/main/java/org/apache/accumulo/core/client/summary/summarizers/AuthorizationSummarizer.java
  core/src/main/java/org/apache/accumulo/core/client/summary/summarizers/VisibilitySummarizer.java
  core/src/test/java/org/apache/accumulo/core/client/summary/summarizers/AuthorizationSummarizerTest.java
Labels: enhancement, v2.0.0
