Repository apache/accumulo, pull requests merged in 2019-03, with the labels that each got.

#1003 Add deprecated methods back with trivial default impl
  core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
Labels: v2.0.0

#1002 Fix implicit casts of numbers & int multiplication
  core/src/main/java/org/apache/accumulo/core/client/lexicoder/UIntegerLexicoder.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/ReplicationClient.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
  core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/lru/LruBlockCache.java
  core/src/main/java/org/apache/accumulo/core/file/blockfile/impl/SeekableByteArrayInputStream.java
  core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java
  core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooSession.java
  server/base/src/main/java/org/apache/accumulo/server/ServerUtil.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/Metrics2ReplicationMetrics.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/ReplicationMetrics.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/ReplicationMetricsMBean.java
  shell/src/main/java/org/apache/accumulo/shell/Shell.java
Labels: v2.0.0

#1000 Simplified options in ClientOpts
  core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
  core/src/main/java/org/apache/accumulo/core/cli/ConfigOpts.java
  core/src/test/java/org/apache/accumulo/core/cli/TestClientOpts.java
  hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/RowHashIT.java
  minicluster/src/main/java/org/apache/accumulo/cluster/AccumuloCluster.java
  minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneAccumuloCluster.java
  minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImpl.java
  server/base/src/main/java/org/apache/accumulo/server/cli/ContextOpts.java
  server/base/src/main/java/org/apache/accumulo/server/cli/ServerUtilOpts.java
  server/base/src/main/java/org/apache/accumulo/server/util/RandomizeVolumes.java
  test/src/main/java/org/apache/accumulo/test/RewriteTabletDirectoriesIT.java
  test/src/main/java/org/apache/accumulo/test/TestBinaryRows.java
  test/src/main/java/org/apache/accumulo/test/TestIngest.java
  test/src/main/java/org/apache/accumulo/test/functional/DeleteIT.java
  test/src/main/java/org/apache/accumulo/test/functional/HalfDeadTServerIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
  test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
  test/src/main/java/org/apache/accumulo/test/functional/RestartStressIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ShutdownIT.java
  test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/MapReduceIT.java
  test/src/main/java/org/apache/accumulo/test/performance/RollWALPerformanceIT.java
  test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
  test/src/test/java/org/apache/accumulo/test/performance/scan/CollectTabletStatsTest.java
Labels: v2.0.0

#1009 Use appropriate types to prevent casting
  core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/TabletLocator.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/TabletServerBatchWriter.java
  core/src/main/java/org/apache/accumulo/core/file/rfile/MultiLevelIndex.java
Labels: v2.0.0

#1008 Make max walogs a tserver property
  core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
  test/src/main/java/org/apache/accumulo/test/performance/RollWALPerformanceIT.java
Labels: v2.0.0

#1012 Support isPropSet for table config
  server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfiguration.java
  server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
  server/base/src/main/java/org/apache/accumulo/server/conf/ZooCachePropertyAccessor.java
Labels: v2.0.0

#1010 Simplified option parsing
  core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
  core/src/main/java/org/apache/accumulo/core/util/Merge.java
  core/src/test/java/org/apache/accumulo/core/cli/TestClientOpts.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/MapReduceClientOnDefaultTable.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/MapReduceClientOnRequiredTable.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/MapReduceClientOpts.java
  hadoop-mapreduce/src/test/java/org/apache/accumulo/hadoop/its/mapreduce/RowHashIT.java
  server/base/src/main/java/org/apache/accumulo/server/cli/ServerUtilOpts.java
  server/base/src/main/java/org/apache/accumulo/server/util/CheckForMetadataProblems.java
  server/base/src/main/java/org/apache/accumulo/server/util/LocalityCheck.java
  server/base/src/main/java/org/apache/accumulo/server/util/RandomWriter.java
  server/base/src/main/java/org/apache/accumulo/server/util/TableDiskUsage.java
  server/base/src/main/java/org/apache/accumulo/server/util/VerifyTabletAssignments.java
  server/master/src/main/java/org/apache/accumulo/master/state/MergeStats.java
  server/tracer/src/main/java/org/apache/accumulo/tracer/TraceDump.java
  server/tracer/src/main/java/org/apache/accumulo/tracer/TraceTableStats.java
  test/src/main/java/org/apache/accumulo/test/TestBinaryRows.java
  test/src/main/java/org/apache/accumulo/test/TestIngest.java
  test/src/main/java/org/apache/accumulo/test/TestMultiTableIngest.java
  test/src/main/java/org/apache/accumulo/test/TestRandomDeletes.java
  test/src/main/java/org/apache/accumulo/test/VerifyIngest.java
  test/src/main/java/org/apache/accumulo/test/functional/BalanceInPresenceOfOfflineTableIT.java
  test/src/main/java/org/apache/accumulo/test/functional/BulkIT.java
  test/src/main/java/org/apache/accumulo/test/functional/BulkSplitOptimizationIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ChaoticBalancerIT.java
  test/src/main/java/org/apache/accumulo/test/functional/CompactionIT.java
  test/src/main/java/org/apache/accumulo/test/functional/DeleteIT.java
  test/src/main/java/org/apache/accumulo/test/functional/DynamicThreadPoolsIT.java
  test/src/main/java/org/apache/accumulo/test/functional/FateStarvationIT.java
  test/src/main/java/org/apache/accumulo/test/functional/FunctionalTestUtils.java
  test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
  test/src/main/java/org/apache/accumulo/test/functional/HalfDeadTServerIT.java
  test/src/main/java/org/apache/accumulo/test/functional/MasterFailoverIT.java
  test/src/main/java/org/apache/accumulo/test/functional/MaxOpenIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
  test/src/main/java/org/apache/accumulo/test/functional/RenameIT.java
  test/src/main/java/org/apache/accumulo/test/functional/RestartIT.java
  test/src/main/java/org/apache/accumulo/test/functional/RestartStressIT.java
  test/src/main/java/org/apache/accumulo/test/functional/SimpleBalancerFairnessIT.java
  test/src/main/java/org/apache/accumulo/test/functional/SplitIT.java
  test/src/main/java/org/apache/accumulo/test/functional/TableIT.java
  test/src/main/java/org/apache/accumulo/test/functional/WriteAheadLogIT.java
  test/src/main/java/org/apache/accumulo/test/functional/WriteLotsIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/RowHash.java
  test/src/main/java/org/apache/accumulo/test/performance/ContinuousIngest.java
  test/src/main/java/org/apache/accumulo/test/performance/scan/CollectTabletStats.java
Labels: v2.0.0

#1014 Replace loops that remove with Collection.removeIf
  core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooCache.java
  server/base/src/main/java/org/apache/accumulo/server/client/BulkImporter.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
  shell/src/main/java/org/apache/accumulo/shell/commands/SetIterCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/SetScanIterCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/SetShellIterCommand.java
  test/src/main/java/org/apache/accumulo/test/InterruptibleScannersIT.java
  test/src/main/java/org/apache/accumulo/test/SampleIT.java
Labels: v2.0.0

#1015 Integration test cleanup
  test/src/main/java/org/apache/accumulo/test/MetaGetsReadersIT.java
  test/src/main/java/org/apache/accumulo/test/MetaRecoveryIT.java
  test/src/main/java/org/apache/accumulo/test/MissingWalHeaderCompletesRecoveryIT.java
  test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
  test/src/main/java/org/apache/accumulo/test/OrIteratorIT.java
  test/src/main/java/org/apache/accumulo/test/RecoveryCompactionsAreFlushesIT.java
  test/src/main/java/org/apache/accumulo/test/RewriteTabletDirectoriesIT.java
  test/src/main/java/org/apache/accumulo/test/SampleIT.java
  test/src/main/java/org/apache/accumulo/test/ScanFlushWithTimeIT.java
  test/src/main/java/org/apache/accumulo/test/SplitCancelsMajCIT.java
  test/src/main/java/org/apache/accumulo/test/SplitRecoveryIT.java
  test/src/main/java/org/apache/accumulo/test/TableOperationsIT.java
  test/src/main/java/org/apache/accumulo/test/TabletServerHdfsRestartIT.java
  test/src/main/java/org/apache/accumulo/test/TotalQueuedIT.java
  test/src/main/java/org/apache/accumulo/test/TracerRecoversAfterOfflineTableIT.java
  test/src/main/java/org/apache/accumulo/test/UserCompactionStrategyIT.java
  test/src/main/java/org/apache/accumulo/test/VerifySerialRecoveryIT.java
  test/src/main/java/org/apache/accumulo/test/VolumeChooserIT.java
  test/src/main/java/org/apache/accumulo/test/VolumeIT.java
  test/src/main/java/org/apache/accumulo/test/YieldScannersIT.java
  test/src/main/java/org/apache/accumulo/test/functional/BatchScanSplitIT.java
  test/src/main/java/org/apache/accumulo/test/functional/BloomFilterIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ConcurrencyIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ConstraintIT.java
  test/src/main/java/org/apache/accumulo/test/functional/CreateAndUseIT.java
  test/src/main/java/org/apache/accumulo/test/functional/DeleteEverythingIT.java
  test/src/main/java/org/apache/accumulo/test/functional/KerberosIT.java
  test/src/main/java/org/apache/accumulo/test/functional/LogicalTimeIT.java
  test/src/main/java/org/apache/accumulo/test/functional/MetadataIT.java
  test/src/main/java/org/apache/accumulo/test/functional/RowDeleteIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ScanIteratorIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ScannerContextIT.java
  test/src/main/java/org/apache/accumulo/test/functional/SummaryIT.java
  test/src/main/java/org/apache/accumulo/test/functional/TimeoutIT.java
  test/src/main/java/org/apache/accumulo/test/gc/replication/CloseWriteAheadLogReferencesIT.java
  test/src/main/java/org/apache/accumulo/test/mapred/AccumuloFileOutputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapred/AccumuloInputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapred/AccumuloMultiTableInputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapred/AccumuloOutputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapred/AccumuloRowInputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloFileOutputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloInputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/AccumuloOutputFormatIT.java
  test/src/main/java/org/apache/accumulo/test/master/MergeStateIT.java
  test/src/main/java/org/apache/accumulo/test/replication/CyclicReplicationIT.java
  test/src/main/java/org/apache/accumulo/test/replication/GarbageCollectorCommunicatesWithTServersIT.java
  test/src/main/java/org/apache/accumulo/test/replication/KerberosReplicationIT.java
  test/src/main/java/org/apache/accumulo/test/replication/MultiInstanceReplicationIT.java
  test/src/main/java/org/apache/accumulo/test/replication/ReplicationIT.java
  test/src/main/java/org/apache/accumulo/test/replication/UnorderedWorkAssignerReplicationIT.java
  test/src/main/java/org/apache/accumulo/test/replication/UnusedWalDoesntCloseReplicationStatusIT.java
Labels: v2.0.0

#999 fixes #998 handle splitting tablet with no data and files
  server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v1.9.3, v2.0.0

#959 Fixes #918 - Clear table problems link on monitor page do nothing.
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/problems/ProblemsResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/util/ParameterValidator.java
  server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/problems.js
Labels: v2.0.0

#1016 improve find split suppression code
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v2.0.0

#1017 Fix some dead logic checks
  server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsConfiguration.java
  server/master/src/main/java/org/apache/accumulo/master/state/MergeStats.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v2.0.0

#1022 Fix NPE in BCFile. Fixes #1021
  core/src/main/java/org/apache/accumulo/core/file/rfile/bcfile/BCFile.java
  core/src/test/java/org/apache/accumulo/core/file/rfile/RFileTest.java
Labels: v2.0.0

#1025 Fix lgtm dead logic alerts
  core/src/main/java/org/apache/accumulo/fate/ZooStore.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v2.0.0

#1028 Fixes #917 - Wrong date on monitor for log recovery.
  server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/master.js
Labels: v2.0.0

#1027 Fix possible bug and improve errors in Tablet
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v2.0.0

#1029 Update to libthrift 0.9.3-1
  pom.xml
Labels: v1.9.3

#1030 Use UncheckedIOException when catching IOException
  server/base/src/main/java/org/apache/accumulo/server/fs/VolumeManagerImpl.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
  shell/src/main/java/org/apache/accumulo/shell/commands/ClasspathCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/MergeCommand.java
  test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java
  test/src/main/java/org/apache/accumulo/test/performance/ContinuousOpts.java
  test/src/main/java/org/apache/accumulo/test/util/SerializationUtil.java
Labels: v2.0.0

#1032 fixes #1031 fix concurrency bug and remove unused code
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CompactionRunner.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v1.9.3, v2.0.0

#1035 Improve DistributedCacheHelper. Closes #896
  core/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/partition/RangePartitioner.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/DistributedCacheHelper.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/partition/RangePartitioner.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/ConfiguratorBase.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/DistributedCacheHelper.java
Labels: v2.0.0

#1038 Fix #976 - Expand overly broad Exceptions in hadoop-mapreduce
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloOutputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloOutputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordReader.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordWriter.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordReader.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordWriter.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/MapReduceClientOpts.java
Labels: v2.0.0

#1046 Updating master metrics to provide FATE operational metrics.
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/MasterMetricsFactory.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetricValues.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetrics.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetricsMBean.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/Metrics2FateMetrics.java
  server/master/src/test/java/org/apache/accumulo/master/metrics/fate/FateMetricValuesTest.java
  test/src/test/resources/hadoop-metrics2-accumulo.properties
Labels: v1.9.3, v2.0.0

#1048 Possible fix and unit test. Fixes #961
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
  server/tserver/src/test/java/org/apache/accumulo/tserver/log/RecoveryLogsReaderTest.java
Labels: v1.9.3, v2.0.0

#1055 Fix #994 Consider mutation queue in example config
  assemble/bin/bootstrap_config.sh
  assemble/conf/templates/accumulo-site.xml
Labels: v1.9.3

#1057 restore exception handling #949 #1005
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
Labels: blocker, v1.9.3
