Repository apache/accumulo, pull requests merged in 2019-04, with the labels that each got.

#1068 Revert commons config to 1.6
  core/src/main/java/org/apache/accumulo/core/client/ClientConfiguration.java
  pom.xml
Labels: v1.9.3

#1070 Fix for #1064.
  server/native/src/main/c++/nativeMap/BlockAllocator.h
  server/native/src/main/c++/nativeMap/NativeMap.h
  server/native/src/main/c++/nativeMap/SubKey.h
Labels: v1.9.3, v2.0.0

#1063 Move metrics registration to master run.
  server/master/src/main/java/org/apache/accumulo/master/Master.java
Labels: v2.0.0

#1059 Switch to thrift server with multiple selector threads.
  server/base/src/main/java/org/apache/accumulo/server/rpc/CustomThreadedSelectorServer.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/ThriftServerType.java
  server/base/src/test/java/org/apache/accumulo/server/rpc/ThriftServerTypeTest.java
Labels: v2.0.0

#1073 Move similar tests into PermissionsIT
  test/src/main/java/org/apache/accumulo/test/ArbitraryTablePropertiesIT.java
  test/src/main/java/org/apache/accumulo/test/functional/PermissionsIT.java
Labels: v2.0.0

#1072 Upgrade jetty to fix CVE
  pom.xml
Labels: v1.9.3

#1075 Revert thrift server to custom_hs_ha
  server/base/src/main/java/org/apache/accumulo/server/rpc/CustomThreadedSelectorServer.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/ThriftServerType.java
  server/base/src/test/java/org/apache/accumulo/server/rpc/ThriftServerTypeTest.java
Labels: v2.0.0

#1061 Improve FateConcurrencyIT test
  test/src/main/java/org/apache/accumulo/test/functional/FateConcurrencyIT.java
Labels: v1.9.3, v2.0.0

#1078 Speed up some longer running ITs
  test/src/main/java/org/apache/accumulo/harness/SharedMiniClusterBase.java
  test/src/main/java/org/apache/accumulo/test/ConditionalWriterIT.java
  test/src/main/java/org/apache/accumulo/test/NamespacesIT.java
  test/src/main/java/org/apache/accumulo/test/functional/BulkLoadIT.java
Labels: v2.0.0

#1034 Fix #933 RuntimeException while stopping Accumulo
  pom.xml
  start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoader.java
Labels: v2.0.0

#1083 Make Monitor service non-static
  server/monitor/pom.xml
  server/monitor/src/main/java/org/apache/accumulo/monitor/EmbeddedWebServer.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/XMLResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/bulkImports/BulkImportResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/gc/GarbageCollectorResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/master/MasterResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/problems/ProblemsResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/replication/ReplicationResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/scans/ScansResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/statistics/StatisticsResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/status/StatusResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tables/TablesResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/trace/TracesResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServer.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerInformation.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
  server/monitor/src/test/java/org/apache/accumulo/monitor/it/WebViewsIT.java
  server/monitor/src/test/java/org/apache/accumulo/monitor/rest/tservers/TabletServerInformationTest.java
Labels: v2.0.0

#1085 fixes #1037 unsynchronzied tablet close state methods
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v2.0.0

#1092 Update Some dependencies
  pom.xml
Labels: v2.0.0

#1097 Include Guava's failureaccess in assembly
  assemble/pom.xml
  assemble/src/main/assemblies/component.xml
  pom.xml
Labels: bug, v2.0.0

#1101 Update Bulk import monitor page. Closes #475
  server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/bulkImport.ftl
Labels: v2.0.0

#1107 Fix ConcurrentModificationException in HostRegexTableLoadBalancer
  server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
Labels: bug, v1.9.4

#1100 Avoid locking in tserver when reading online tablets
  server/tserver/src/main/java/org/apache/accumulo/tserver/OnlineTablets.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsUtil.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/BulkImportCacheCleaner.java
Labels: v2.0.0

#1103 Create AbstractServer type for Accumulo servers
  server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
  server/base/src/main/java/org/apache/accumulo/server/ServerContext.java
  server/gc/src/main/java/org/apache/accumulo/gc/GCExecutable.java
  server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
  server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorOptsTest.java
  server/gc/src/test/java/org/apache/accumulo/gc/SimpleGarbageCollectorTest.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/EmbeddedWebServer.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/Monitor.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/MonitorExecutable.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Labels: v2.0.0

#1130 Fixes #593 Hide Master is Down message on startup
  server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/overview.ftl
Labels: v2.0.0

#1088 Fix #1087, wrap FileWriter with BufferedWriter
  server/base/src/main/java/org/apache/accumulo/server/util/Admin.java
Labels: v2.0.0

#1127 fixes #1111 support reading unencrypted WALs from 1.9
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
  test/src/main/java/org/apache/accumulo/test/TestIngest.java
  test/src/main/java/org/apache/accumulo/test/VerifyIngest.java
Labels: v2.0.0
