Repository apache/accumulo, pull requests merged in 2019-05, with the labels that each got.

#1144 Attempt #1 to fix Assembly runtime issues
  assemble/src/main/assemblies/component.xml
Labels: v2.0.0

#1147 Cleanup monitor CSS
  server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/css/screen.css
Labels: v2.0.0

#1145 fix #1141 adding checks for extra FATE RPC arguments
  server/master/src/main/java/org/apache/accumulo/master/FateServiceHandler.java
Labels: v1.9.4, v2.0.0

#1149 Drop Server Activity page from Monitor
  server/monitor/src/main/java/org/apache/accumulo/monitor/view/WebViews.java
  server/monitor/src/main/resources/org/apache/accumulo/monitor/resources/js/vis.js
  server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/navbar.ftl
  server/monitor/src/main/resources/org/apache/accumulo/monitor/templates/vis.ftl
Labels: v2.0.0

#1140 Deprecate cumbersome CLI scan options
  shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
Labels: v2.0.0

#1154 Handle shell scan error messages consistently
  shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
Labels: v2.0.0

#1156 Add missing LRUMap generic parameters
  core/src/main/java/org/apache/accumulo/core/client/rfile/RFileWriter.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/ConditionalWriterImpl.java
  core/src/main/java/org/apache/accumulo/core/iterators/system/VisibilityFilter.java
  core/src/main/java/org/apache/accumulo/core/iterators/user/TransformingIterator.java
  core/src/main/java/org/apache/accumulo/core/iterators/user/VisibilityFilter.java
  server/base/src/main/java/org/apache/accumulo/server/problems/ProblemReports.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogReader.java
  shell/src/main/java/org/apache/accumulo/shell/commands/TablesCommand.java
Labels: v2.0.0

#1157 fix #1153 preventing multiple threads working on same bulk file
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: bug, v1.9.4, v2.0.0

#1125 Fixes #1119 - Improve Retry code
  core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
  core/src/main/java/org/apache/accumulo/fate/util/Retry.java
  core/src/main/java/org/apache/accumulo/fate/zookeeper/ZooUtil.java
  core/src/test/java/org/apache/accumulo/fate/util/RetryTest.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
Labels: v2.0.0

#1163 Remove direct uses of log4j
  assemble/conf/log4j.properties
  core/pom.xml
  core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/SyncingTabletLocator.java
  core/src/test/java/org/apache/accumulo/core/file/rfile/MultiThreadedRFileTest.java
  core/src/test/java/org/apache/accumulo/core/file/rfile/RFileMetricsTest.java
  core/src/test/java/org/apache/accumulo/core/iterators/system/VisibilityFilterTest.java
  core/src/test/java/org/apache/accumulo/core/iterators/user/IndexedDocIteratorTest.java
  hadoop-mapreduce/pom.xml
  minicluster/pom.xml
  minicluster/src/test/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloClusterImplTest.java
  pom.xml
  server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfWatcher.java
  server/base/src/main/java/org/apache/accumulo/server/conf/TableConfWatcher.java
  server/base/src/main/java/org/apache/accumulo/server/util/DumpZookeeper.java
  server/base/src/main/java/org/apache/accumulo/server/util/RestoreZookeeper.java
  server/base/src/test/java/org/apache/accumulo/server/constraints/MetadataConstraintsTest.java
  server/tserver/pom.xml
  server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/strategies/BasicCompactionStrategy.java
  server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
  server/tserver/src/test/java/org/apache/accumulo/tserver/log/TestUpgradePathForWALogs.java
  shell/pom.xml
  shell/src/main/java/org/apache/accumulo/shell/Shell.java
  shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
  shell/src/main/java/org/apache/accumulo/shell/commands/AddAuthsCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/CompactCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/ConfigCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/CreateTableCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/CreateUserCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/DebugCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/DeleteAuthsCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/DeleteScanIterCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/DeleteShellIterCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/DropUserCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/FlushCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/GrantCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/InsertCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/OfflineCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/OnlineCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/PasswdCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/RevokeCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/ScanCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/SetAuthsCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/SetScanIterCommand.java
  shell/src/main/java/org/apache/accumulo/shell/commands/TraceCommand.java
  shell/src/main/java/org/apache/accumulo/shell/format/DeleterFormatter.java
  shell/src/test/java/org/apache/accumulo/shell/ShellConfigTest.java
  start/pom.xml
  start/src/test/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoaderTest.java
  test/src/main/java/org/apache/accumulo/test/BatchWriterInTabletServerIT.java
  test/src/main/java/org/apache/accumulo/test/HardListIterator.java
  test/src/main/java/org/apache/accumulo/test/ShellIT.java
  test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
  test/src/main/java/org/apache/accumulo/test/TestIngest.java
  test/src/main/java/org/apache/accumulo/test/performance/ContinuousOpts.java
  test/src/main/java/org/apache/accumulo/test/rpc/ThriftBehaviorIT.java
Labels: v2.0.0

#1170 Update jackson to 2.9.9
  pom.xml
Labels: blocker, v2.0.0

#1172 Remove option for legacy metrics.
  assemble/conf/templates/accumulo-metrics.xml
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  proxy/src/main/java/org/apache/accumulo/proxy/Proxy.java
  server/base/pom.xml
  server/base/src/main/java/org/apache/accumulo/server/metrics/AbstractMetricsImpl.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsConfiguration.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsFactory.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/ThriftMetrics.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/ThriftMetricsMBean.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/TimedProcessor.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/MasterMetricsFactory.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/ReplicationMetrics.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/ReplicationMetricsMBean.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetricValues.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetrics.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetricsMBean.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMBean.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMBeanImpl.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsFactory.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMinCMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMinCMetricsMBean.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetricsMBean.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerUpdateMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerUpdateMetricsMBean.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v2.0.0
