Repository apache/accumulo, pull requests merged in 2019-01, with the labels that each got.

#840 fixes #819 Handle bad locality group config.
  core/src/main/java/org/apache/accumulo/core/client/admin/NewTableConfiguration.java
  core/src/main/java/org/apache/accumulo/core/client/impl/InstanceOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/NamespaceOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/util/LocalityGroupUtil.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Compactor.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/MinorCompactor.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletMemory.java
  server/tserver/src/test/java/org/apache/accumulo/tserver/InMemoryMapTest.java
  test/src/main/java/org/apache/accumulo/test/InMemoryMapIT.java
  test/src/main/java/org/apache/accumulo/test/InMemoryMapMemoryUsageTest.java
  test/src/main/java/org/apache/accumulo/test/functional/BadLocalityGroupMincIT.java
  test/src/main/java/org/apache/accumulo/test/functional/RowDeleteIT.java
Labels: v1.9.3, v2.0.0

#845 fixes #823 unreference closed WALs that were never written to
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/DfsLogger.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/TabletServerLogger.java
Labels: v1.9.3, v2.0.0

#860 Fixes #854 handle many tablets referencing many WALs
  core/src/main/java/org/apache/accumulo/core/client/impl/TableOperationsImpl.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
  test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
  test/src/main/java/org/apache/accumulo/test/functional/WALSunnyDayIT.java
Labels: v1.9.3, v2.0.0

#866 Fix race condition when getting WALs for dead tserver
  server/base/src/main/java/org/apache/accumulo/server/log/WalStateManager.java
Labels: blocker, bug, v1.9.3, v2.0.0

#863 Remove unused tserver code
  server/tserver/src/main/java/org/apache/accumulo/tserver/InMemoryMap.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/NativeMap.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/MajorCompactionRequest.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/compaction/strategies/TooManyDeletesCompactionStrategy.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/CommitSession.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/ScanOptions.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletCommitter.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletData.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/TabletMemory.java
Labels: v2.0.0

#872 Remove 'accumulo-util hadoop-jar' command
  assemble/bin/accumulo-util
  minicluster/src/main/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControl.java
  minicluster/src/test/java/org/apache/accumulo/cluster/standalone/StandaloneClusterControlTest.java
Labels: v2.0.0

#870 Remove unused code in master and server
  server/base/src/main/java/org/apache/accumulo/server/init/Initialize.java
  server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
  server/base/src/main/java/org/apache/accumulo/server/replication/ReplicationUtil.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/SaslServerConnectionParams.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
  server/base/src/main/java/org/apache/accumulo/server/security/SecurityUtil.java
  server/base/src/main/java/org/apache/accumulo/server/security/UserImpersonation.java
  server/base/src/main/java/org/apache/accumulo/server/security/handler/InsecureAuthenticator.java
  server/base/src/main/java/org/apache/accumulo/server/security/handler/InsecurePermHandler.java
  server/base/src/main/java/org/apache/accumulo/server/security/handler/PermissionHandler.java
  server/base/src/main/java/org/apache/accumulo/server/tables/TableManager.java
  server/base/src/test/java/org/apache/accumulo/server/replication/ReplicationUtilTest.java
  server/master/src/main/java/org/apache/accumulo/master/TabletGroupWatcher.java
  server/master/src/main/java/org/apache/accumulo/master/replication/DistributedWorkQueueWorkAssigner.java
  server/master/src/main/java/org/apache/accumulo/master/replication/SequentialWorkAssigner.java
  server/master/src/main/java/org/apache/accumulo/master/replication/StatusMaker.java
  server/master/src/main/java/org/apache/accumulo/master/replication/WorkDriver.java
  server/master/src/main/java/org/apache/accumulo/master/util/TableValidators.java
Labels: v2.0.0

#868 Make replication services start when configured
  server/master/src/main/java/org/apache/accumulo/master/Master.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  test/src/main/java/org/apache/accumulo/test/replication/MultiTserverReplicationIT.java
Labels: v2.0.0

#878 Cleanup params in PermissionHandler
  server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
  server/base/src/main/java/org/apache/accumulo/server/security/handler/KerberosPermissionHandler.java
  server/base/src/main/java/org/apache/accumulo/server/security/handler/PermissionHandler.java
  server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKPermHandler.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
Labels: v2.0.0

#879 Fix latest round of warnings
  core/src/main/java/org/apache/accumulo/core/client/ZooKeeperInstance.java
  core/src/test/java/org/apache/accumulo/core/file/rfile/KeyShortenerTest.java
  server/base/src/main/java/org/apache/accumulo/server/ServerInfo.java
  server/base/src/main/java/org/apache/accumulo/server/util/MasterMetadataUtil.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
Labels: v2.0.0

#881 During tablet recovery filter logs out that do not define tablet.
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/RecoveryLogsIterator.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/log/SortedLogRecovery.java
Labels: v1.9.3, v2.0.0

#871 Check transaction are alive for new bulk import RPCs
  core/src/main/java/org/apache/accumulo/core/tabletserver/thrift/TabletClientService.java
  core/src/main/thrift/tabletserver.thrift
  server/base/src/main/java/org/apache/accumulo/server/zookeeper/TransactionWatcher.java
  server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/LoadFiles.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  test/src/main/java/org/apache/accumulo/test/functional/BulkFailureIT.java
  test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
Labels: v2.0.0

#887 Fix #885 Simplify 'accumulo classpath' command
  assemble/bin/accumulo
  core/src/main/java/org/apache/accumulo/core/util/Classpath.java
  start/src/main/java/org/apache/accumulo/start/Main.java
  test/src/main/java/org/apache/accumulo/test/start/KeywordStartIT.java
Labels: v2.0.0

#884 Clean up new Map Reduce internals
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloFileOutputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloInputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloOutputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapred/AccumuloRowInputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloFileOutputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloInputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloOutputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/AccumuloRowInputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AbstractInputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloFileOutputFormatImpl.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloOutputFormatImpl.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordReader.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/AccumuloRecordWriter.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapred/InputFormatBase.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AbstractInputFormat.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloFileOutputFormatImpl.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloOutputFormatImpl.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordReader.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/AccumuloRecordWriter.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/FileOutputFormatBuilderImpl.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/InputFormatBase.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/InputFormatBuilderImpl.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/InputTableConfig.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/OutputFormatBuilderImpl.java
Labels: v2.0.0

#892 Revert core/mapred* serialization
  core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
  core/src/main/java/org/apache/accumulo/core/client/mapred/AbstractInputFormat.java
  core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloFileOutputFormat.java
  core/src/main/java/org/apache/accumulo/core/client/mapred/AccumuloOutputFormat.java
  core/src/main/java/org/apache/accumulo/core/client/mapred/InputFormatBase.java
  core/src/main/java/org/apache/accumulo/core/client/mapreduce/AbstractInputFormat.java
  core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloFileOutputFormat.java
  core/src/main/java/org/apache/accumulo/core/client/mapreduce/AccumuloOutputFormat.java
  core/src/main/java/org/apache/accumulo/core/client/mapreduce/InputFormatBase.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/ConnectorImpl.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBase.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/FileOutputConfigurator.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/InputConfigurator.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/OutputConfigurator.java
  core/src/test/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBaseTest.java
  test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/RowHash.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/TokenFileIT.java
Labels: v2.0.0

#895 Fix SslIT integration tests
  test/src/main/java/org/apache/accumulo/test/mapreduce/MapReduceIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/RowHash.java
  test/src/main/resources/log4j.properties
Labels: v2.0.0

#903 Upgrade jackson to 2.9.8
  pom.xml
Labels: v2.0.0

#889 fixes #736 avoid dropping exceptions in scanner
  core/src/main/java/org/apache/accumulo/core/client/TableDeletedException.java
  core/src/main/java/org/apache/accumulo/core/client/TableOfflineException.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/IsolationException.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/ScannerIterator.java
Labels: v2.0.0

#890 Organize new Bulk Import code
  core/src/main/java/org/apache/accumulo/core/clientImpl/TableOperationsImpl.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/Bulk.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkImport.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/BulkSerialize.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCache.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/bulk/LoadMappingIterator.java
  core/src/test/java/org/apache/accumulo/core/clientImpl/bulk/BulkSerializeTest.java
  core/src/test/java/org/apache/accumulo/core/clientImpl/bulk/ConcurrentKeyExtentCacheTest.java
  server/base/src/main/java/org/apache/accumulo/server/util/FileUtil.java
  server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/BulkImportMove.java
  server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/LoadFiles.java
  server/master/src/main/java/org/apache/accumulo/master/tableOps/bulkVer2/PrepBulkImport.java
Labels: v2.0.0

#904 Exclude vuln thrift dep from build
  pom.xml
Labels: v2.0.0
