Repository apache/accumulo, pull requests merged in 2019-06, with the labels that each got.

#1175 Clean up and refactor metrics for maintainability
  proxy/src/main/java/org/apache/accumulo/proxy/Proxy.java
  server/base/src/main/java/org/apache/accumulo/server/AbstractServer.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/Metrics.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/Metrics2ThriftMetrics.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/MetricsSystemHelper.java
  server/base/src/main/java/org/apache/accumulo/server/metrics/ThriftMetrics.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/TServerUtils.java
  server/base/src/main/java/org/apache/accumulo/server/rpc/TimedProcessor.java
  server/base/src/test/java/org/apache/accumulo/server/util/TServerUtilsTest.java
  server/gc/src/main/java/org/apache/accumulo/gc/SimpleGarbageCollector.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/MasterMetrics.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/MasterMetricsFactory.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/ReplicationMetrics.java
  server/master/src/main/java/org/apache/accumulo/master/metrics/fate/FateMetrics.java
  server/master/src/test/java/org/apache/accumulo/master/metrics/ReplicationMetricsTest.java
  server/tracer/src/main/java/org/apache/accumulo/tracer/TraceServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerMinCMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerScanMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/Metrics2TabletServerUpdateMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TServerMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsFactory.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMetricsKeys.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerMinCMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerScanMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/metrics/TabletServerUpdateMetrics.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
  test/src/main/java/org/apache/accumulo/test/functional/ZombieTServer.java
  test/src/main/java/org/apache/accumulo/test/performance/NullTserver.java
Labels: v2.0.0

#1176 Update to commons-configuration2.5
  assemble/pom.xml
  assemble/src/main/assemblies/component.xml
  core/pom.xml
  core/src/main/java/org/apache/accumulo/core/client/ClientConfiguration.java
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  core/src/main/java/org/apache/accumulo/core/conf/SiteConfiguration.java
  core/src/main/java/org/apache/accumulo/core/file/blockfile/cache/impl/ClassSize.java
  minicluster/pom.xml
  minicluster/src/main/java/org/apache/accumulo/cluster/RemoteShellOptions.java
  minicluster/src/test/java/org/apache/accumulo/minicluster/MiniAccumuloClusterTest.java
  pom.xml
  start/pom.xml
  start/src/main/java/org/apache/accumulo/start/classloader/AccumuloClassLoader.java
  test/pom.xml
  test/src/main/java/org/apache/accumulo/harness/conf/AccumuloClusterPropertyConfiguration.java
  test/src/main/java/org/apache/accumulo/test/RewriteTabletDirectoriesIT.java
  test/src/main/java/org/apache/accumulo/test/VolumeIT.java
Labels: v2.0.0

#1164 Fix #1084 partial - IT tests failing on Standalone
  test/src/main/java/org/apache/accumulo/harness/AccumuloClusterHarness.java
  test/src/main/java/org/apache/accumulo/test/IteratorEnvIT.java
  test/src/main/java/org/apache/accumulo/test/functional/AccumuloClientIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ManyWriteAheadLogsIT.java
  test/src/main/java/org/apache/accumulo/test/functional/ReadWriteIT.java
  test/src/main/java/org/apache/accumulo/test/functional/YieldingIterator.java
Labels: v2.0.0

#1179 Remove custom property interpolations
  assemble/src/main/assemblies/component.xml
  core/src/main/java/org/apache/accumulo/core/Constants.java
  core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
  core/src/main/java/org/apache/accumulo/core/conf/ConfigurationDocGen.java
  core/src/main/java/org/apache/accumulo/core/conf/Interpolated.java
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  core/src/main/java/org/apache/accumulo/core/conf/PropertyType.java
  core/src/test/java/org/apache/accumulo/core/conf/PropertyTest.java
  core/src/test/java/org/apache/accumulo/core/security/VisibilityConstraintTest.java
  minicluster/src/main/java/org/apache/accumulo/miniclusterImpl/MiniAccumuloConfigImpl.java
  start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java
  start/src/test/java/org/apache/accumulo/start/classloader/vfs/AccumuloReloadingVFSClassLoaderTest.java
  start/src/test/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoaderTest.java
Labels: v2.0.0

#1178 Fix #418 Javadoc updated with workaround for createIfNotExists
  core/src/main/java/org/apache/accumulo/core/client/admin/NamespaceOperations.java
  core/src/main/java/org/apache/accumulo/core/client/admin/TableOperations.java
Labels: v2.0.0

#1185 Ensures correct use of ZooKeeper getAcl
  fate/src/main/java/org/apache/accumulo/fate/zookeeper/ZooReader.java
  fate/src/main/java/org/apache/accumulo/fate/zookeeper/ZooUtil.java
  pom.xml
Labels: v1.9.4, v2.0.0

#1188 Improve the use of Hadoop's DistributedCache
  core/src/main/java/org/apache/accumulo/core/client/mapreduce/lib/partition/RangePartitioner.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/ConfiguratorBase.java
  core/src/main/java/org/apache/accumulo/core/clientImpl/mapreduce/lib/DistributedCacheHelper.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoop/mapreduce/partition/RangePartitioner.java
  hadoop-mapreduce/src/main/java/org/apache/accumulo/hadoopImpl/mapreduce/lib/ConfiguratorBase.java
  shell/src/main/java/org/apache/accumulo/shell/ShellOptionsJC.java
  shell/src/test/java/org/apache/accumulo/shell/PasswordConverterTest.java
  test/src/main/java/org/apache/accumulo/test/mapred/TokenFileIT.java
  test/src/main/java/org/apache/accumulo/test/mapreduce/TokenFileIT.java
Labels: v2.0.0

#1184 fixed time calculation to use nano delta
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
Labels: v1.9.4, v2.0.0

#1201 fix #1123 replace observing config with continual derivation
  core/src/main/java/org/apache/accumulo/core/conf/AccumuloConfiguration.java
  core/src/main/java/org/apache/accumulo/core/conf/ConfigurationObserver.java
  core/src/main/java/org/apache/accumulo/core/conf/ObservableConfiguration.java
  core/src/test/java/org/apache/accumulo/core/conf/ObservableConfigurationTest.java
  server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfWatcher.java
  server/base/src/main/java/org/apache/accumulo/server/conf/NamespaceConfiguration.java
  server/base/src/main/java/org/apache/accumulo/server/conf/ServerConfigurationFactory.java
  server/base/src/main/java/org/apache/accumulo/server/conf/TableConfWatcher.java
  server/base/src/main/java/org/apache/accumulo/server/conf/TableConfiguration.java
  server/base/src/main/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancer.java
  server/base/src/test/java/org/apache/accumulo/server/conf/NamespaceConfigurationTest.java
  server/base/src/test/java/org/apache/accumulo/server/conf/ServerConfigurationFactoryTest.java
  server/base/src/test/java/org/apache/accumulo/server/conf/TableConfigurationTest.java
  server/base/src/test/java/org/apache/accumulo/server/master/balancer/BaseHostRegexTableLoadBalancerTest.java
  server/base/src/test/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancerReconfigurationTest.java
  server/base/src/test/java/org/apache/accumulo/server/master/balancer/HostRegexTableLoadBalancerTest.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/constraints/ConstraintChecker.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/tablet/Tablet.java
  server/tserver/src/test/java/org/apache/accumulo/tserver/tablet/TabletTest.java
Labels: v2.1.0

#1204 Allow master start to block waiting for a number of tservers
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  server/master/src/main/java/org/apache/accumulo/master/Master.java
Labels: v2.0.0

#1205 Fix #822 Add thread-safety info to AccumuloClient javadoc
  core/src/main/java/org/apache/accumulo/core/client/AccumuloClient.java
Labels: v2.0.0

#1197 Added a catch all for dropped Client properties.
  core/src/main/java/org/apache/accumulo/core/cli/ClientOpts.java
Labels: v2.0.0

#1213 Fix bad unit tests found while building on Java 11
  core/src/test/java/org/apache/accumulo/core/data/NamespaceIdTest.java
  core/src/test/java/org/apache/accumulo/core/data/TableIdTest.java
  pom.xml
  start/src/main/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoader.java
  start/src/test/java/org/apache/accumulo/start/classloader/vfs/AccumuloVFSClassLoaderTest.java
Labels: v2.0.0

#1215 Fix more tests building 2.0 with Java 11
  assemble/pom.xml
  assemble/src/main/assemblies/component.xml
  pom.xml
  server/monitor/pom.xml
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServer.java
  server/tserver/src/main/java/org/apache/accumulo/tserver/TabletServerResourceManager.java
  server/tserver/src/test/java/org/apache/accumulo/tserver/TabletServerResourceManagerDynamicCompactionPoolTest.java
  test/src/main/java/org/apache/accumulo/test/ShellServerIT.java
  test/src/main/java/org/apache/accumulo/test/functional/DynamicThreadPoolsIT.java
  test/src/main/java/org/apache/accumulo/test/functional/GarbageCollectorIT.java
Labels: v2.0.0
