Repository apache/accumulo, pull requests merged in 2020-12, with the labels that each got.

#1827 Fix unneeded audit message about denial
  server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
Labels: bug

#1828 Throw exceptions when permissions checks fail
  server/manager/src/main/java/org/apache/accumulo/master/MasterClientServiceHandler.java
Labels: blocker, bug

#1830 Throw sercurity exceptions when permissions checks fail. Backport to 1.10
  server/master/src/main/java/org/apache/accumulo/master/MasterClientServiceHandler.java
  test/src/main/java/org/apache/accumulo/test/AuditMessageIT.java
Labels: blocker, bug

#1831 Remove a redundant audit message
  server/base/src/main/java/org/apache/accumulo/server/security/SecurityOperation.java
Labels: bug

#1834 Remove centralized crypto constants
  core/src/main/java/org/apache/accumulo/core/Constants.java
  core/src/main/java/org/apache/accumulo/core/conf/Property.java
  core/src/main/java/org/apache/accumulo/core/dataImpl/KeyExtent.java
  core/src/main/java/org/apache/accumulo/core/file/rfile/VisMetricsGatherer.java
  server/base/src/main/java/org/apache/accumulo/server/security/SystemCredentials.java
  server/base/src/main/java/org/apache/accumulo/server/security/handler/ZKSecurityTool.java
  server/base/src/test/java/org/apache/accumulo/server/security/SystemCredentialsTest.java
  server/monitor/src/main/java/org/apache/accumulo/monitor/rest/tservers/TabletServerResource.java
  shell/src/main/java/org/apache/accumulo/shell/commands/GetSplitsCommand.java
Labels: enhancement
